name: "Verify the code"

on:
  push

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Get cache for local Maven repository
        uses: actions/cache/restore@v4
        with:
          path: ~/.m2/repository
          key: maven-verify
      - name: Verify the bot
        run: mvn --batch-mode --update-snapshots verify --file pom.xml
